#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Validate reviewed metadata and generate Rust identifiers; never execute recipes."""
import argparse
import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CATALOG = ROOT / 'catalog/components.json'
OUTPUT = ROOT / 'crates/functional-core/assbox-domain/src/component_ids.rs'


def read_catalog():
    rows = json.loads(CATALOG.read_text())
    ids = [r['id'] for r in rows]
    if len(ids) > 64:
        raise ValueError('component selection representation supports at most 64 IDs')
    if ids != sorted(set(ids)):
        raise ValueError('catalog identifiers must be unique and sorted')
    exports = set()
    for row in rows:
        if set(row) != {'id', 'package', 'family', 'command', 'dependencies', 'presentations', 'unfree', 'mutableCode', 'blocked', 'codeNotes', 'controllerAllowed', 'workerAllowed', 'requiresWorker'}:
            raise ValueError('unexpected catalog fields')
        if not re.fullmatch(r'[a-z][a-z0-9-]*', row['id']):
            raise ValueError('invalid component identifier')
        if type(row['unfree']) is not bool or type(row['mutableCode']) is not bool:
            raise ValueError('invalid consent metadata')
        if any(type(row[field]) is not bool for field in ('controllerAllowed', 'workerAllowed', 'requiresWorker')):
            raise ValueError('invalid placement metadata')
        if row['workerAllowed'] and 'headless' not in row['presentations']:
            raise ValueError('worker component must support headless execution')
        if row['controllerAllowed'] and row['workerAllowed']:
            raise ValueError('controller and execution packages cannot be interchangeable')
        if any(not isinstance(row[field], str) for field in ['blocked', 'codeNotes']):
            raise ValueError('invalid disclosure metadata')
        if not row['presentations'] or not set(row['presentations']) <= {'headless', 'x11', 'wayland'}:
            raise ValueError('invalid presentation')
        for field in ['family', 'package', 'command']:
            if row[field] and not re.fullmatch(r'[a-z][a-z0-9-]*', row[field]):
                raise ValueError('invalid catalog package/family/command')
        if len(set(row['dependencies'])) != len(row['dependencies']):
            raise ValueError('duplicate dependency')
        if row['command']:
            if row['command'] in exports:
                raise ValueError('duplicate executable export')
            exports.add(row['command'])
        if any(d not in ids for d in row['dependencies']):
            raise ValueError('unknown dependency')
    by_id = {r['id']: r for r in rows}
    def visit(id, active):
        if id in active:
            raise ValueError('dependency cycle')
        for dep in by_id[id]['dependencies']:
            visit(dep, active | {id})
    for id in ids:
        visit(id, set())
    return rows


def variant(id):
    return ''.join(s.capitalize() for s in id.split('-'))


def generate(rows):
    out = '// SPDX-License-Identifier: GPL-3.0-or-later\n// Generated by scripts/component_catalog.py. Do not edit.\n'
    out += 'use crate::{Error, Result, Presentation};\nuse std::{fmt, str::FromStr};\n'
    out += 'named_enum!(Component {\n'
    out += ''.join(f'    {variant(r["id"])} => "{r["id"]}",\n' for r in rows) + '});\n'
    out += 'impl Component {\n    pub const ALL: &\'static [Self] = &[\n'
    out += ''.join(f'        Self::{variant(r["id"])},\n' for r in rows) + '    ];\n'
    for name, field, typ in [('dependencies','dependencies',"&'static [Component]"),('presentations','presentations',"&'static [Presentation]"),('unfree','unfree','bool'),('mutable_code','mutableCode','bool'),('blocked','blocked',"&'static str"),('command','command',"&'static str"),('code_notes','codeNotes',"&'static str"),('controller_allowed','controllerAllowed','bool'),('worker_allowed','workerAllowed','bool'),('requires_worker','requiresWorker','bool')]:
        out += f'    pub const fn {name}(self) -> {typ} {{\n        match self {{\n'
        for r in rows:
            v = r[field]
            if field in ('dependencies','presentations'):
                owner = 'Self' if field == 'dependencies' else 'Presentation'
                val = '&[' + ', '.join(f'{owner}::{variant(d)}' for d in v) + ']'
            else:
                val = json.dumps(v)
            out += f'            Self::{variant(r["id"])} => {val},\n'
        out += '        }\n    }\n'
    families = sorted({r['family'] for r in rows} - {'nixpkgs'})
    check = ' and '.join(f'. != "{f}-packages"' for f in families)
    out += '}\n' + f'pub const RELEASE_HELD_INPUT_CHECK: &str = {json.dumps(check)};\n'
    return subprocess.run(['rustfmt', '--edition', '2024'], input=out, text=True, capture_output=True, check=True).stdout


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    rows = read_catalog()
    generated = generate(rows)
    families = sorted({r['family'] for r in rows} - {'nixpkgs'})
    family_path = ROOT / 'scripts/component_families.py'
    family_text = '# SPDX-License-Identifier: GPL-3.0-or-later\n# Generated by component_catalog.py.\nFAMILIES = ' + repr(tuple(families)) + '\n'
    if args.check:
        if family_path.read_text() != family_text:
            raise SystemExit('component release-family drift')
    else:
        family_path.write_text(family_text)
    if args.check:
        if OUTPUT.read_text() != generated:
            raise SystemExit('component metadata drift: run python3 scripts/component_catalog.py')
    else:
        OUTPUT.write_text(generated)
