# SPDX-License-Identifier: GPL-3.0-or-later
# Generated by component_catalog.py.
FAMILIES = ('antigravity', 'chatgpt', 'claude-code', 'claude-desktop', 'codex', 'cursor', 'grok', 'happier', 'hermes', 'omp', 'openclaw', 'opencode', 'pi')
