#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Compile reviewed preset data into pure Rust values. No runtime recipes."""
import argparse
import json
from pathlib import Path
import subprocess
from component_catalog import read_catalog, variant

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / 'crates/functional-core/assbox-domain/src/preset_ids.rs'


def read_presets():
    catalog = {r['id']: r for r in read_catalog()}
    rows = json.loads((ROOT / 'catalog/presets.json').read_text())
    if [r['id'] for r in rows] != sorted({r['id'] for r in rows}):
        raise ValueError('preset identifiers must be unique and sorted')
    for row in rows:
        if set(row) != {'id', 'purpose', 'revision', 'components', 'presentation', 'tailscale', 'workloadSsh', 'webApps'}:
            raise ValueError('unexpected preset fields')
        if row['purpose'] not in ['assistant', 'coder', 'kiosk', 'custom'] or type(row['revision']) is not int or row['revision'] < 1:
            raise ValueError('invalid preset provenance')
        if row['presentation'] not in ['headless', 'x11', 'wayland'] or any(type(row[k]) is not bool for k in ('tailscale', 'workloadSsh')):
            raise ValueError('invalid preset capability defaults')
        if not set(row['components']) <= catalog.keys() or len(row['components']) != len(set(row['components'])):
            raise ValueError('invalid preset components')
        if any(not set(catalog[c]['dependencies']) <= set(row['components']) for c in row['components']):
            raise ValueError('preset omits required dependencies')
        if not set(row['webApps']) <= {'chatgpt', 'claude'} or len(row['webApps']) != len(set(row['webApps'])):
            raise ValueError('invalid preset web apps')
    return rows


def generate():
    text = '// SPDX-License-Identifier: GPL-3.0-or-later\n// Generated by scripts/preset_catalog.py.\nuse crate::{Component, Presentation};\nuse crate::instances::{Preset, Purpose};\npub const PRESETS: &[Preset] = &[\n'
    for row in read_presets():
        components = ', '.join('Component::' + variant(c) for c in row['components'])
        web_apps = ', '.join(json.dumps(a) for a in row['webApps'])
        text += f'Preset {{ id: {json.dumps(row["id"])}, purpose: Purpose::{variant(row["purpose"])}, revision: {row["revision"]}, components: &[{components}], presentation: Presentation::{variant(row["presentation"])}, tailscale: {str(row["tailscale"]).lower()}, workload_ssh: {str(row["workloadSsh"]).lower()}, web_apps: &[{web_apps}] }},\n'
    text += '];\n'
    return subprocess.run(['rustfmt', '--edition', '2024'], input=text, text=True,
                          capture_output=True, check=True).stdout


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    text = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != text:
            raise SystemExit('preset metadata drift: run scripts/preset_catalog.py')
    else:
        OUTPUT.write_text(text)
