#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Render reviewed catalog and dated evidence. No network or runtime capability rules."""
import argparse
from datetime import date
import json
from pathlib import Path
import re
from component_catalog import read_catalog
from preset_catalog import read_presets

ROOT = Path(__file__).resolve().parent.parent
GENERATED = '<!-- Generated by scripts/product_docs.py; update the reviewed data, then regenerate. -->\n'


def cell(value):
    return str(value).replace('|', '\\|').replace('\n', ' ')


def ids(values):
    return ', '.join('`' + value + '`' for value in values) or 'none'


def catalog_page():
    output = GENERATED + '''# Presets and component catalog

These tables use the same reviewed [preset](../../catalog/presets.json) and
[component](../../catalog/components.json) data as the installer. They describe
initial selections, not installed state or qualification. Individual exclusions
are recorded in generated ordinary Nix settings. Later catalog changes do not
expand an existing machine's selection. Raw module components remain opt-in.

## Guided presets

Tailscale support does not enroll the machine or publish a service. Execution
computer use starts off. The native kiosk is staged until its exact policy gate
passes; its optional protected Code worker is a separate explicit choice.

| Preset | Purpose / revision | Initially checked components | Presentation | Tailscale support | Workload SSH | Web apps |
|---|---|---|---|---|---|---|
'''
    for row in read_presets():
        values = [f'`{row["id"]}`', f'{row["purpose"]} / {row["revision"]}', ids(row['components']),
                  row['presentation'], 'yes' if row['tailscale'] else 'no',
                  'yes' if row['workloadSsh'] else 'no', ids(row['webApps'])]
        output += '| ' + ' | '.join(cell(v) for v in values) + ' |\n'
    output += '''
## Components

Package families are independently held release inputs. Empty command/package
entries represent an integration or service choice, not an extra runtime. Mutable
helper consent and unfree package consent are separate. Placement eligibility
never grants native local-execution authority or proves a transport works.

| ID | Held family | Package / command | Required components | Presentation | Placement | Consent / limitation |
|---|---|---|---|---|---|---|
'''
    for row in read_catalog():
        placement = 'controller' if row['controllerAllowed'] else ('execution / worker' if row['workerAllowed'] else 'standalone')
        consent = (['unfree'] if row['unfree'] else []) + (['mutable helpers'] if row['mutableCode'] else [])
        if row['blocked']:
            consent.append(row['blocked'])
        values = [f'`{row["id"]}`', row['family'], f'{row["package"] or "—"} / {row["command"] or "—"}',
                  ids(row['dependencies']), ', '.join(row['presentations']), placement, '; '.join(consent) or 'none']
        output += '| ' + ' | '.join(cell(v) for v in values) + ' |\n'
    return output + '''
Provider setup, actual transport and integration maturity are described in
[applications](../applications.md) and [Coder routes](coder-options.md).
[Implementation status](../implementation-status.md) distinguishes present
mechanisms from release qualification.
'''


def sources(values, anchors):
    if not values or any(not re.fullmatch(r'S[0-9]{2}', value) or value.lower() not in anchors for value in values):
        raise ValueError('invalid dated evidence source reference')
    return ', '.join(f'[{value}](sources.md#{value.lower()})' for value in values)


def evidence_page():
    data = json.loads((ROOT / 'qualification/linux-computer-use.json').read_text())
    requirements = {r['id'] for r in json.loads((ROOT / 'qualification/acceptance.json').read_text())}
    anchors = set(re.findall(r'<a id="([^"]+)"', (ROOT / 'docs/product/sources.md').read_text()))
    date.fromisoformat(data['reviewed_local_date'])
    output = GENERATED + f'# Linux browser and computer-use support\n\n**Reviewed:** {data["reviewed_local_date"]}. **Scope:** {data["scope"]}\n\n'
    output += '''This dated upstream evidence is separate from Assbox qualification. Each row
records its own Assbox status and evidence. The selected application,
authentication mode, package/helper build and display backend require actual
release tests before being advertised as qualified. This table is never loaded
as an installer resolver rule or fetched at boot.

| Product path | Linux browser actions | Linux arbitrary desktop control | Sources | Assbox qualification |
|---|---|---|---|---|
'''
    seen = set()
    for row in data['rows']:
        if row['id'] in seen or not re.fullmatch(r'CU[0-9]{2}', row['id']):
            raise ValueError('invalid dated evidence identifier')
        seen.add(row['id'])
        date.fromisoformat(row['reviewed_local_date'])
        if not set(row['requirements']) <= requirements:
            raise ValueError('unknown dated evidence requirement')
        if row['assbox_status'] == 'passed' and not row['evidence']:
            raise ValueError('qualification pass requires evidence')
        source_links = sources(row['sources'], anchors)
        values = [row['path'], row['browser'], row['desktop'], source_links, row['assbox_status'].replace('_', ' ')]
        output += '| ' + ' | '.join(cell(v) for v in values) + ' |\n'
    output += '\n## Exact-path qualifications\n\nRequirement IDs identify acceptance work in the [release ledger](../../qualification/acceptance.json). Upstream evidence cannot silently promote a row to an Assbox pass.\n'
    for row in data['rows']:
        evidence = cell(json.dumps(row['evidence'], sort_keys=True)) if row['evidence'] else 'no evidence'
        output += f'\n### {row["id"]} — {row["path"]}\n\n**Reviewed:** {row["reviewed_local_date"]}. **Assbox status:** {row["assbox_status"].replace("_", " ")}; {evidence}.\n\n'
        output += f'**Scope and limits:** {row["scope"]}\n\n**Implementation requirement:** {row["implementation"]}\n\n**Qualification references:** {", ".join(row["requirements"])}.\n\n**Upstream evidence:** {sources(row["sources"], anchors)}.\n'
    return output + '''
## How to use this evidence

A limitation of a native consumer application is not a limitation of the same
model used through another Linux-capable harness. An API or alternative harness
needs its own tools, authentication and qualification.

Browser automation is not arbitrary desktop control. A virtual display is an
execution resource and does not isolate same-UID agents. Installing Xvfb cannot
enable an unsupported native feature. Current upstream documentation and
otherwise compiled binaries do not override evidence about the selected closure.

Update the reviewed JSON when qualifying a release, retaining source date,
package revision, compiled features and test record. Missing or stale evidence
is neither a pass nor proof that a route cannot work. Stable environment and
authority rules are in [computer-use policy](computer-use.md). The
[source register](sources.md) preserves provider claims and dates.
'''


def outputs():
    return {
        ROOT / 'docs/product/component-presets.md': catalog_page(),
        ROOT / 'docs/product/linux-computer-use-support.md': evidence_page(),
    }


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, text in outputs().items():
        if args.check:
            if not path.exists() or path.read_text() != text:
                raise SystemExit(f'generated product documentation drift: {path.relative_to(ROOT)}')
        else:
            path.write_text(text)
